version: "3"

services:
  web:
    container_name: async_download_service
    restart: always

    build:
      context: .
      dockerfile: Dockerfile

    ports:
      - 8080:8080

    volumes:
      - .:/project
      - ./test_photos:/project/test_photos

    command: python server.py --log --timeout 1
